{{- if .Values.kimball.enableDaemonset -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "kimball-api.fullname" . }}
  labels:
    {{- include "kimball-api.labels" . | nindent 4 }}
spec:
  minReadySeconds: 30
  selector:
    matchLabels:
      {{- include "kimball-api.DSSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kimball-api.DSSelectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: features-data
          configMap:
            name: features-state-store
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              hostPort: {{ .Values.kimball.daemonsetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /alive
              port: http
          readinessProbe:
            httpGet:
              path: /alive
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- if .Values.kimball.sentry_dsn }}
          - name: "SENTRY_DSN"
            valueFrom:
              secretKeyRef:
                name: {{ include "kimball-api.fullname" . }}
                key: sentry_dsn
          {{- end }}
          - name: "ANALYTICS_HOST"
            value: {{ include "kimball-api.fullname" . }}
          - name: "FEATURES_MODE"
            value: sidecar
          - name: LOG_LEVEL
            value: {{ .Values.kimball.logLevel }}
          volumeMounts:
          - name: features-data
            mountPath: /features
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
