apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kimball-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kimball-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 30
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "kimball-api.APISelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kimball-api.APISelectorLabels" . | nindent 8 }}
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
    {{- end }}
      serviceAccountName: {{ include "kimball-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /alive
              port: http
          readinessProbe:
            httpGet:
              path: /alive
              port: http
          resources:
            {{- toYaml .Values.deploymentResources | nindent 12 }}
          env:
          {{- if .Values.kimball.sentry_dsn }}
          - name: "SENTRY_DSN"
            valueFrom:
              secretKeyRef:
                name: {{ include "kimball-api.fullname" . }}
                key: sentry_dsn
          {{- end }}
          - name: "ADDITIONAL_NAMESPACES"
            value: {{ .Release.Namespace }}
          - name: "FEATURES_MODE"
            value: {{ .Values.kimball.mode }}
          - name: LOG_LEVEL
            value: {{ .Values.kimball.logLevel }}
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: S3_BUCKET
            value: {{ .Values.kimball.s3_bucket }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
