---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kimball-api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - apps
  - ''
  resources:
  - 'configmaps'
  verbs:
  - get
  - list
  - status
  - update
- apiGroups:
  - apps
  - ''
  resources:
  - 'configmaps'
  verbs:
  # Create can't be restricted by resource name
  - create
