---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: getkimball
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "kimball-api.serviceAccountName" . }}
roleRef:
  kind: Role
  name: getkimball
  apiGroup: rbac.authorization.k8s.io
