apiVersion: v1
kind: Secret
type: Opaque
data:
  {{- if .Values.kimball.sentry_dsn }}
  sentry_dsn: {{ .Values.kimball.sentry_dsn | b64enc }}
  {{- else }}
  sentry_dsn: ""
  {{- end }}
metadata:
  name: {{ include "kimball-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
